# Generated by Django 5.0.3 on 2024-05-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_delete_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.FileField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
