# Generated by Django 5.0.3 on 2024-05-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uplodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='img',
            name='sal',
            field=models.FloatField(default=0),
        ),
    ]
