# Generated by Django 5.0.3 on 2024-05-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
