# Generated by Django 5.0.3 on 2024-05-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.TextField(default=0, max_length=50),
        ),
    ]
