# Generated by Django 5.0.3 on 2024-05-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.FileField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
