# Generated by Django 5.0.3 on 2024-05-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=100)),
                ('img', models.FileField(upload_to='image1')),
            ],
        ),
    ]
