# Generated by Django 5.0.3 on 2024-04-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='singup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(default='babu@gmail.com', max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=25)),
                ('compass', models.CharField(max_length=25)),
            ],
        ),
    ]
