# Generated by Django 5.0.3 on 2024-04-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singup',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='singup',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
