# Generated by Django 5.0.3 on 2024-04-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0002_alter_singup_name_alter_singup_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singup',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='singup',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
