# Generated by Django 5.0.3 on 2024-04-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0003_alter_singup_email_alter_singup_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singup',
            name='name',
            field=models.CharField(default=3, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='singup',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
